### ISSUE TITLE
build error: RollupError: Entry module cannot be external

### ISSUE THREAD

**Issue by felixsanz** [milahu/lezer-parser-nix#3]
can you, please?

**Comment by milahu** [comment]
nope

all package managers support install from git

```sh
cd $(mktemp -d)
npm init -y

# one of ...
yarn add https://github.com/milahu/lezer-parser-nix#86fe7185f0c4f0ec72c3eb2c5b431ff9a55d13b3
pnpm i https://github.com/milahu/lezer-parser-nix#86fe7185f0c4f0ec72c3eb2c5b431ff9a55d13b3
npm i https://github.com/milahu/lezer-parser-nix#86fe7185f0c4f0ec72c3eb2c5b431ff9a55d13b3

grep lezer-parser-nix package.json
#     "lezer-parser-nix": "github:milahu/lezer-parser-nix#86fe7185f0c4f0ec72c3eb2c5b431ff9a55d13b3"
```

`npm i` takes forever, but thats not my problem

closing

**Comment by felixsanz** [comment]
@milahu  well... the problem is that this package is broken on windows, because the `npm run build` script doesn't run successfully. If you publish to npm, the `dist` folder is served via npm and the build script doesn't have to run, that's why I was asking if you could upload to npm.

the noderesolve() thing inside rollup config is what makes this break on windows. Any idea? I never used rollup so I couldn't find a workaround :/

**Comment by milahu** [comment]
> this package is broken on windows, because the `npm run build` script doesn't run successfully

aah, thats the issue

please try 946c8ad71fb294a01c3a9d0b347ce8723072ce63

**Comment by felixsanz** [comment]
> > this package is broken on windows, because the `npm run build` script doesn't run successfully
> 
> aah, thats the issue
> 
> please try [946c8ad](https://github.com/milahu/lezer-parser-nix/commit/946c8ad71fb294a01c3a9d0b347ce8723072ce63)

still happening the same issue.

```
npm ERR! > lezer-generator src/nix.grammar -o src/parser && rollup -c
npm ERR!
npm ERR! Wrote src/parser.js and src/parser.terms.js
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR!
npm ERR! ./src/index.js → ./dist/index.cjs, ./dist/index.js...
npm ERR! [!] RollupError: Entry module "./src/index.js" cannot be external.
```

the `rollup -c` command is the one that fails

**Comment by milahu** [comment]
weird

this parser is based on https://github.com/lezer-parser/html

do you get the same error with

```
npm install https://github.com/lezer-parser/html
```

related isues: ["RollupError: Entry module" "cannot be external"](https://github.com/search?q=%22RollupError%3A+Entry+module%22+%22cannot+be+external%22&type=issues)

https://github.com/nuxt/nuxt/issues/24551#issuecomment-1838066114

> I've deleted yarn.lock and node_modules and installed everything again, and now the error seems to be gone

please try

```
rm -rf node_modules
rm package-lock.json
npm install
```

https://github.com/Septh/rollup-plugin-node-externals/issues/20

> Maybe it's related to the patch `Consider an empty include option means 'includes all'.`

**Comment by felixsanz** [comment]
> weird
> 
> this parser is based on [lezer-parser/html](https://github.com/lezer-parser/html) do you get the same error with
> 
> ```
> npm install https://github.com/lezer-parser/html
> ```
> 
> related issues: ["RollupError: Entry module" "cannot be external"](https://github.com/search?q=%22RollupError%3A+Entry+module%22+%22cannot+be+external%22&type=issues)
> 
> [nuxt/nuxt#24551 (comment)](https://github.com/nuxt/nuxt/issues/24551#issuecomment-1838066114)
> 
> > I've deleted yarn.lock and node_modules and installed everything again, and now the error seems to be gone
> 
> please try
> 
> ```
> rm -rf node_modules
> rm package-lock.json
> npm install
> ```
> 
> [Septh/rollup-plugin-node-externals#20](https://github.com/Septh/rollup-plugin-node-externals/issues/20)
> 
> > Maybe it's related to the patch `Consider an empty include option means 'includes all'.`

Deleting node_modules won't help as I'm also trying on a freshly new folder:

Full log:

```
~\Desktop
❯ mkdir foo

~\Desktop
❯ cd foo

~\Desktop\foo
❯ npm init -y
Wrote to C:\Users\felixsanz\Desktop\foo\package.json:

~\Desktop\foo is 📦 v1.0.0 via  v21.4.0
❯ npm install https://github.com/lezer-parser/html

added 4 packages, and audited 5 packages in 22s

found 0 vulnerabilities

~\Desktop\foo is 📦 v1.0.0 via  v21.4.0 took 23s
❯ npm install https://github.com/milahu/lezer-parser-nix
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\felixsanz\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > lezer-parser-nix@0.1.10 prepare
npm ERR! > npm run build
npm ERR!
npm ERR!
npm ERR! > lezer-parser-nix@0.1.10 build
npm ERR! > lezer-generator src/nix.grammar -o src/parser && rollup -c
npm ERR!
npm ERR! Wrote src/parser.js and src/parser.terms.js
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR!
npm ERR! ./src/index.js → ./dist/index.cjs, ./dist/index.js...
npm ERR! [!] RollupError: Entry module "./src/index.js" cannot be external.
npm ERR!     at Object.error (C:\Users\felixsanz\AppData\Local\npm-cache\_cacache\tmp\git-cloneoNXfYb\node_modules\rollup\dist\shared\parseAst.js:279:30)
npm ERR!     at ModuleLoader.loadEntryModule (C:\Users\felixsanz\AppData\Local\npm-cache\_cacache\tmp\git-cloneoNXfYb\node_modules\rollup\dist\shared\rollup.js:19068:32)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at async Promise.all (index 0)
npm ERR!
npm ERR!
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path C:\Users\felixsanz\AppData\Local\npm-cache\_cacache\tmp\git-cloneoNXfYb
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm run build
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in: C:\Users\felixsanz\AppData\Local\npm-cache\_logs\2023-12-27T22_58_30_682Z-debug-0.log

npm ERR! A complete log of this run can be found in: C:\Users\felixsanz\AppData\Local\npm-cache\_logs\2023-12-27T22_58_25_388Z-debug-0.log
```

**Comment by milahu** [comment]
thx. please try 9251a188b4deeb48017dc3b16a43fbf893e4a905

or generally, try to make `lezer-parser-nix` more similar to `lezer-parser-html`

```
git clone --depth=1 https://github.com/lezer-parser/html lezer-parser-html
git clone  --depth=1 https://github.com/milahu/lezer-parser-nix
cd lezer-parser-nix
function _diff() { diff -y ../lezer-parser-html/"$1" "$1"; }
_diff package.json
```

**Comment by felixsanz** [comment]
> thx. please try [9251a18](https://github.com/milahu/lezer-parser-nix/commit/9251a188b4deeb48017dc3b16a43fbf893e4a905)

Using `"@rollup/plugin-node-resolve": "^9.0.0",` fixes the install issue, but there must be a build problem because there are only this files in the `dist` folder:

```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        28/12/2023     14:22            257 index.cjs
-a----        28/12/2023     14:22             59 index.d.ts
-a----        28/12/2023     14:22            122 index.js
```

and index.js contents is this:

```js
export { parser } from './parser.js';

//import * as props from "./props" // FIXME
const props = null;

export { props };
```

It's trying call parser.js, and it doesn't exist. So it crash.

```
 error   Cannot find module 'C:\Users\felixsanz\asdas\node_modules\lezer-parser-nix\dist\parser.js' imported from C:\Users\felixsanz\asdas\node_modules\lezer-parser-nix\dist\index.js
```

**Comment by milahu** [comment]
should be fixed now

i removed the `prepare` script and committed the `dist/*` files
this also makes the install faster

**Comment by felixsanz** [comment]
> should be fixed now

the install issue seems fixed, but i can't get the parser to work, maybe it's how I use it? but i've been using a lot of parsers without issue:

```js
// I import parsers like this
import { parser as bashParser } from '@fig/lezer-bash'
import { parser as nixParser } from 'lezer-parser-nix'
import { parser as phpParser } from '@lezer/php'
```

and then I use:

```js
const tree = nixParser.parse(source)

highlightTree(tree, classHighlighter, (from: number, to: number, classes: string) => {
  tokens.push({ from, to, classes })
})
```

It works fine with all other parsers but not with nix one. Any idea why?

I'm parsing this:

```nix
{ pkgs, lib, ... }:

{
  programs.firefox.enable = true;
  programs.firefox.userChrome = builtins.readFile ./userChrome.css;
}
```

**Comment by milahu** [comment]
sorry, this is embarassing .__.

on my end, it works with

```
$ node src/nix-parse-cli.js -e 1+1
Expr(Add(Int,Int))
```

which does

```js
import {parser} from "../dist/index.js"
const tree = parser.parse(text);
console.log(stringifyTree(tree));
```

so `nixParser.parse` should work, and maybe `highlightTree` fails?

---

maybe because `props` is missing in `index.js`?

```
import {parser} from "./parser"
//import * as props from "./props" // FIXME
const props = null

export {parser, props}
```

please try

```diff
-export {parser, props}
+export {parser}
```

---

lezer-parser-html has a [highlight.js](https://github.com/lezer-parser/html/blob/main/src/highlight.js) file, which is loaded by [html.grammar](https://github.com/lezer-parser/html/blob/main/src/html.grammar)

```
@external propSource htmlHighlighting from "./highlight"
```

here is a working live demo with codemirror: [nix-eval-js](https://milahu.github.io/nix-eval-js/demo/dist/)
but that is using [codemirror-lang-nix](https://github.com/milahu/codemirror-lang-nix)

[codemirror.jsx](https://github.com/milahu/nix-eval-js/blob/main/demo/src/codemirror.jsx)

<details>

```js
import { nix as codemirrorLangNix } from "./codemirror-lang-nix/dist/index.js";
//import { javascript } from "@codemirror/lang-javascript";

// ...

    const basicSetupSolid = {
// ...
      codemirrorLangNix: codemirrorLangNix({
        data: {
          autocomplete: props.onAutoComplete,
        }
      }),
// ...
    };

    for (const [extensionName, extension] of Object.entries(basicSetupSolid)) {
      const reconfigureExtension = createExtension(extension);
      codeMirrorExtensions[extensionName] = {
        extension,
        reconfigure: reconfigureExtension,
      };
    }
```

</details>

**Comment by felixsanz** [comment]
> sorry, this is embarassing .__.

no! you're actually dedicating time to it, which I thank you very much

> so `nixParser.parse` should work, and maybe `highlightTree` fails?

yes, `parse` seems to give the tree correctly, but `highlightTree` seems unable to produce token information from the tree?

> maybe because `props` is missing in `index.js`?
>
> please try
> 
> ```diff
> -export {parser, props}
> +export {parser}
> ```

it doesn't fix it. in fact looks no different

> lezer-parser-html has a [highlight.js](https://github.com/lezer-parser/html/blob/main/src/highlight.js) file, which is loaded by [html.grammar](https://github.com/lezer-parser/html/blob/main/src/html.grammar)

I'm pretty sure this is the issue. lezer-parser-html has this `styleTags()` that seems to be the information about tokens so `highlightTree` will learn what to do with the tree. The html parser has it but the nix one does not, because this is moved to the codemirror package instead (milahu/codemirror-lang-nix).

> can you show your `highlightTree` function?

it's the official one from `lezer` package: https://lezer.codemirror.net/docs/ref/#highlight.highlightTree

> Highlight the given [tree](https://lezer.codemirror.net/docs/ref/#common.Tree) with the given [highlighter](https://lezer.codemirror.net/docs/ref/#highlight.Highlighter). Often, the higher-level [highlightCode](https://lezer.codemirror.net/docs/ref/#highlight.highlightCode) function is easier to use.

The `highlighter` thing is the thing missing here, as you pointed out:

```
@external propSource htmlHighlighting from "./highlight"
```

I don't know what are the options here. I can't fix this in my code right? The grammar should include this line so the parser handles token information too, but you have separated the parser from the codemirror related stuff in 2 different repos, not sure if you want this "fixed" or I should fork the project for my own needs?

**Comment by felixsanz** [comment]
JSON parser is a simpler one and a good example. https://github.com/lezer-parser/json/tree/main/src

At the bottom of the grammar it has this:

```
@external propSource jsonHighlighting from "./highlight"
```

So maybe you just need to add this:

```
@external propSource nixHighlighting from "./highlight"
```

and then creating `highlight.js` with this content (extracted from milahu/codemirror-lang-nix):

```js
import {styleTags, tags as t} from "@lezer/highlight"

export const nixHighlighting = styleTags({
  Identifier: t.propertyName,
  TRUE: t.bool,
  FALSE: t.bool,
  String: t.string,
  StringContent: t.string,
  IndentedString: t.string,
  IndentedStringContent: t.string,
  Comment: t.lineComment,
  CommentBlock: t.blockComment,
  Float: t.float,
  Integer: t.integer,
  NULL: t.null,
  URI: t.url,
  //SPath: t.literal, // TODO what is stringpath? not implemented in nix.grammar
  Path: t.literal,
  "( )": t.paren,
  "{ }": t.brace,
  "[ ]": t.squareBracket,
  "if then else": t.controlKeyword,
  "import with let in rec builtins inherit assert or": t.keyword,
})
```

What do you think?

**Comment by milahu** [comment]
done

**Comment by felixsanz** [comment]
> done

yay! we got it! thank you so much!!! 🙏🙏

![image](https://github.com/milahu/lezer-parser-nix/assets/6182099/3e47c4ed-f508-48b5-ad29-282db8387dce)

**Comment by milahu** [comment]
yay : )

i have also updated [codemirror-lang-nix](https://github.com/milahu/codemirror-lang-nix)
